common: &common_settings
  recaptcha_public_key: ""
  recaptcha_private_key: ""

development: &development_settings
  backup_root_name: "Wbox"
  backup_destination_path: "/Wbox/"
  backup_name_pattern: "WB{bid}__u{uid}__{profile_name}" 


test: &test_settings

production: &production_settings
